name = "queueit_regnos"
type = "javascript"
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-04-21"
account_id = 'b4338a7810e7ca32677c67cdc69ba9ba'
kv_namespaces = [
    { binding = 'IntegrationConfigKV', id = '7771db17323b47489faa9dc1bf627160' },
    { binding = 'CognitoJWK', id = '1bcc393909f34166bfeb8eb0ec1d2e29' }
]
